image: "python:3.7"

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - python --version
    
test-job:
  stage: test
  before_script:
    - pip install pytest
  script:
    - pytest --version